### ISSUE TITLE
Change sign when multiply(bug)

### ISSUE THREAD

**Issue by XumeraHz** [bazzilic/BigInteger#27]
Unpleasant bug.
```
BigInteger int3 = new BigInteger("-100", 10);
BigInteger int4 = new BigInteger("-3", 10);
BigInteger int5 = new BigInteger("0", 10);
int5 = int3 * int4;
```
The numbers used in "int3" and "int4" when multiplying will change their sign to "+" if there were "-".

```
public static BigInteger operator *(BigInteger bi1, BigInteger bi2)
...
       try
            {
                if ((bi1.data[lastPos] & 0x80000000) != 0)     // bi1 negative
                {
                    bi1Neg = true; bi1 = -bi1;
                }
                if ((bi2.data[lastPos] & 0x80000000) != 0)     // bi2 negative
                {
                    bi2Neg = true; bi2 = -bi2;
                }
            }
            catch (Exception) { }
```

p.s. sorry for my English

**Comment by bazzilic** [comment]
Thanks for the bug report. This library is not really supported anymore since .NET Framework introduced their own internal implementation of BigInteger class. If you would like to find the source of the bug and submit a PR, we can merge the fix from you. I can't give any timeline on when we will be able to investigate the issue.

**Comment by furun** [comment]
I could not reproduce the bug.
Can you give a example?
