### ISSUE TITLE
Clarification about "maxLength"

### ISSUE THREAD

**Issue by slumdroid** [bazzilic/BigInteger#32]
Hello @bazzilic ,

I am trying different values of maxlength in search of the optimal value for my "calculations".
I setted it to "320" and "384"...

Can you give me more information so I can effectively and efficiently choose the value of maxlength, please?
Thanks

**Comment by bazzilic** [comment]
That depends on your calculations. `maxLength` sets the maximum potential size of the integer at ~ 2^(8×4×`maxLength`). For `maxLength` = 10, max value of integer is ~2^320. IIRC, for the majority (for all?) of the algorithms used in this implementation, `maxLength` does not directly affect performance, just the memory requirements.

Take note that this repo is not maintained, and you would be better off using the `System.Numerics.BigInteger` struct that is available since .NET Framework v4.0.

**Comment by slumdroid** [comment]
Hello @bazzilic,

Thanks for your quick response, and for your precious feedback.
I used the BigInteger v1.0.3 and recently I found this repository (I am happy to discover that you correct known bugs).
I am trying it, and for the moment I have only positive feedback about this.

For future works, I will try to use directly "System.Numerics.BigInteger", if it will be necessary.

Thanks
Best Regards
